vim.cmd [[autocmd Filetype markdown setlocal colorcolumn=80]]
vim.cmd [[autocmd! BufNewFile,BufRead *.vs,*.fs set ft=glsl]]
vim.cmd [[autocmd Filetype htmldjango :syntax sync fromstart]]
-- vim.cmd [[autocmd Filetype tex setlocal wrap]]
vim.cmd [[autocmd Filetype tex setlocal textwidth=100]]
-- vim.cmd [[autocmd Filetype tex nnoremap <leader>b :TexlabBuild<CR>]]
vim.cmd [[autocmd Filetype tex nnoremap <leader>b :silent :make -s SRC=%<CR>]]
vim.cmd [[autocmd Filetype c,cpp setlocal commentstring=//\ %s]]
vim.cmd [[autocmd TextYankPost * lua vim.highlight.on_yank() ]]
